### ISSUE TITLE
树莓派4B使用最新容器镜像CPU占用过高问题

### ISSUE THREAD

**Issue by SoraKasvgano** [unifreq/openwrt_packit#70]
大佬您好，新装镜像里面 有一个 登录脚本总是占用很高的CPU 有没有什么解决方案，网上查了半天没有查到，

/sbin/askfirst /usr/libexec/login.sh

基本上占满独立的一个核心

**Comment by SoraKasvgano** [comment]
![捕获](https://user-images.githubusercontent.com/8521327/157050121-178b148f-21bc-43ef-8932-04b281b74bd8.JPG)
![2](https://user-images.githubusercontent.com/8521327/157050140-62d7224b-e0a8-47d4-ad3a-8505b4b659bf.JPG)
![222](https://user-images.githubusercontent.com/8521327/157050148-a2afc00d-532a-4df7-bca7-208982156b04.JPG)

**Comment by unifreq** [comment]
我没做过树莓pi4b的固件啊，不清楚是怎么回事，这个login.sh是用lede源码编译的，所以有问题也只会是lede源码的问题
----- 原始邮件 -----
发件人：Sora ***@***.***>
收件人：unifreq/openwrt_packit ***@***.***>
抄送人：Subscribed ***@***.***>
主题：Re:_[unifreq/openwrt_packit]_树莓派4B使用最新容器镜像CPU占用过高问题_(Issue_#70)
日期：2022年03月07日 22点11分













&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SoraKasvgano** [comment]
> 我没做过树莓pi4b的固件啊，不清楚是怎么回事，这个login.sh是用lede源码编译的，所以有问题也只会是lede源码的问题 ----- 原始邮件 ----- 发件人：Sora ***@***.***> 收件人：unifreq/openwrt_packit ***@***.***> 抄送人：Subscribed ***@***.***> 主题：Re:_[unifreq/openwrt_packit]_树莓派4B使用最新容器镜像CPU占用过高问题_(Issue_#70) 日期：2022年03月07日 22点11分 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

是的 确实比较奇怪，按道理讲 docker 镜像 跑在任何ARM设备上都应该是一样的。。。。

但是N1 用容器跑 最新的镜像就没问题，RPI4跑最新的镜像就是CPU占用异常 麻了

**Comment by unifreq** [comment]
可能是你用的armbian内核缺少某些驱动模块发自我的华为手机-------- 原始邮件 --------发件人： Sora ***@***.***>日期： 2022年3月11日周五 16:36收件人： unifreq/openwrt_packit ***@***.***>抄送： unifreq ***@***.***>, Comment ***@***.***>主    题： Re: [unifreq/openwrt_packit] 树莓派4B使用最新容器镜像CPU占用过高问题 (Issue #70)



我没做过树莓pi4b的固件啊，不清楚是怎么回事，这个login.sh是用lede源码编译的，所以有问题也只会是lede源码的问题 ----- 原始邮件 ----- 发件人：Sora @.> 收件人：unifreq/openwrt_packit @.> 抄送人：Subscribed @.> 主题：Re:[unifreq/openwrt_packit]树莓派4B使用最新容器镜像CPU占用过高问题(Issue#70) 日期：2022年03月07日 22点11分 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: @.>



是的 确实比较奇怪，按道理讲 docker 镜像 跑在任何ARM设备上都应该是一样的。。。。

但是N1 用容器跑 最新的镜像就没问题，RPI4跑最新的镜像就是CPU占用异常 麻了

**Comment by zzbajie** [comment]
进入openwrt：

vi /etc/inittab

注释后边三条带askfirst的项目
#ttyAMA0::askfirst:/usr/libexec/login.sh
#ttyS0::askfirst:/usr/libexec/login.sh
#hvc0::askfirst:/usr/libexec/login.sh

reboot

**Comment by blight19** [comment]
> 进入openwrt：
> 
> vi /etc/inittab
> 
> 注释后边三条带askfirst的项目 #ttyAMA0::askfirst:/usr/libexec/login.sh #ttyS0::askfirst:/usr/libexec/login.sh #hvc0::askfirst:/usr/libexec/login.sh
> 
> reboot

好用
