### ISSUE TITLE
hk1 的 usb 3.0 插着网卡启动导致网卡无法使用

### ISSUE THREAD

**Issue by puteulanus** [unifreq/openwrt_packit#81]
hk1 box 刷 68+o、70+o、71+ 都遇到了这个问题，其他版本没来得及测了

只要 USB 3.0 的口子插着 USB 有线网卡启动，有相当高的几率启动之后网卡无法使用，情况主要分两类：

1. lsusb 命令卡死，能看到 USB 网卡的句柄，echo > unbind 卡死，重拔插网卡无效
日志：
```
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.648887] usb 2-1: new SuperSpeed USB device number 9 using xhci-hcd
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.666526] usb 2-1: New USB device found, idVendor=0bda, idProduct=8153, bcdDevice=30.00
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.671005] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=6
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.678119] usb 2-1: Product: USB 10/100/1000 LAN
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.682663] usb 2-1: Manufacturer: Realtek
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.686756] usb 2-1: SerialNumber: 000001
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.891685] usb 2-1: reset SuperSpeed USB device number 9 using xhci-hcd
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.952499] r8152 2-1:1.0: load rtl8153a-4 v2 02/07/20 successfully
Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.983336] r8152 2-1:1.0 eth1: v1.12.12
Tue Apr 19 14:40:24 2022 cron.err crond[7153]: crond (busybox 1.35.0) started, log level 5
Tue Apr 19 14:40:25 2022 daemon.notice netifd: Interface 'WAN' is enabled
Tue Apr 19 14:40:25 2022 kern.warn kernel: [   25.907956] r8152 2-1:1.0 eth1: intr_urb submit failed: -19
```

2. 反复 reset 直到失败，重拔插网卡后可以识别并使用
日志：
```
Tue Apr 19 14:42:55 2022 kern.info kernel: [   55.982386] usb 2-1: reset SuperSpeed USB device number 13 using xhci-hcd
Tue Apr 19 14:42:56 2022 kern.info kernel: [   56.789064] usb 2-1: reset SuperSpeed USB device number 13 using xhci-hcd
Tue Apr 19 14:42:56 2022 kern.err kernel: [   56.808147] usb 2-1: device descriptor read/8, error -71
Tue Apr 19 14:42:56 2022 kern.info kernel: [   56.915544] usb 2-1: reset SuperSpeed USB device number 13 using xhci-hcd
Tue Apr 19 14:42:57 2022 user.notice nlbwmon: Reloading nlbwmon due to ifup of loopback (lo)
Tue Apr 19 14:42:57 2022 kern.info kernel: [   57.355579] usb 2-1: USB disconnect, device number 13
Tue Apr 19 14:42:57 2022 kern.warn kernel: [   57.545609] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:42:57 2022 kern.warn kernel: [   57.755565] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:42:57 2022 kern.err kernel: [   57.962210] usb 2-1: device not accepting address 14, error -71
Tue Apr 19 14:42:58 2022 kern.warn kernel: [   58.152279] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:42:58 2022 kern.warn kernel: [   58.358948] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:42:58 2022 kern.err kernel: [   58.568939] usb 2-1: device not accepting address 15, error -71
Tue Apr 19 14:42:58 2022 kern.info kernel: [   58.570949] usb usb2-port1: attempt power cycle
Tue Apr 19 14:42:59 2022 kern.warn kernel: [   59.958894] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:43:00 2022 kern.warn kernel: [   60.165563] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:43:00 2022 kern.err kernel: [   60.372178] usb 2-1: device not accepting address 16, error -71
Tue Apr 19 14:43:00 2022 kern.warn kernel: [   60.772293] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:43:00 2022 kern.warn kernel: [   60.982259] usb 2-1: Device not responding to setup address.
Tue Apr 19 14:43:01 2022 kern.err kernel: [   61.188864] usb 2-1: device not accepting address 17, error -71
Tue Apr 19 14:43:01 2022 kern.err kernel: [   61.190765] usb usb2-port1: unable to enumerate USB device
```

目前只能在每次重启的时候先拔下 USB 网卡，重启之后再插回去。
插在 USB 2.0 口子上重启了两三次试了下，好像 2.0 的口没有这个问题。

请问这个是已知问题吗，有什么解决办法吗（换网卡，换某一版本的系统，延时启动的 usb hub?）

**Comment by unifreq** [comment]
这基本上是hk1box本身的体质问题，一是usb口接触不良，二是供电电源纹波太大，重点是第二条，可通过更换优质电源适配器以及在hk1的主板上把电解电容换成固态电容，换电容效果很明显。
----- 原始邮件 -----
发件人：Puteulanus ***@***.***>
收件人：unifreq/openwrt_packit ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[unifreq/openwrt_packit]_hk1_的_usb_3.0_插着网卡启动导致网卡无法使用_(Issue_#81)
日期：2022年04月19日 15点49分



hk1 box 刷 68+o、70+o、71+ 都遇到了这个问题，其他版本没来得及测了

只要 USB 3.0 的口子插着 USB 有线网卡启动，有相当高的几率启动之后网卡无法使用，情况主要分两类：



lsusb 命令卡死，能看到 USB 网卡的句柄，echo > unbind 卡死，重拔插网卡无效


日志：



Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.648887] usb 2-1: new SuperSpeed USB device number 9 using xhci-hcd

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.666526] usb 2-1: New USB device found, idVendor=0bda, idProduct=8153, bcdDevice=30.00

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.671005] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=6

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.678119] usb 2-1: Product: USB 10/100/1000 LAN

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.682663] usb 2-1: Manufacturer: Realtek

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.686756] usb 2-1: SerialNumber: 000001

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.891685] usb 2-1: reset SuperSpeed USB device number 9 using xhci-hcd

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.952499] r8152 2-1:1.0: load rtl8153a-4 v2 02/07/20 successfully

Tue Apr 19 14:40:24 2022 kern.info kernel: [   24.983336] r8152 2-1:1.0 eth1: v1.12.12

Tue Apr 19 14:40:24 2022 cron.err crond[7153]: crond (busybox 1.35.0) started, log level 5

Tue Apr 19 14:40:25 2022 daemon.notice netifd: Interface 'WAN' is enabled

Tue Apr 19 14:40:25 2022 kern.warn kernel: [   25.907956] r8152 2-1:1.0 eth1: intr_urb submit failed: -19





反复 reset 直到失败，重拔插网卡后可以识别并使用


日志：



Tue Apr 19 14:42:55 2022 kern.info kernel: [   55.982386] usb 2-1: reset SuperSpeed USB device number 13 using xhci-hcd

Tue Apr 19 14:42:56 2022 kern.info kernel: [   56.789064] usb 2-1: reset SuperSpeed USB device number 13 using xhci-hcd

Tue Apr 19 14:42:56 2022 kern.err kernel: [   56.808147] usb 2-1: device descriptor read/8, error -71

Tue Apr 19 14:42:56 2022 kern.info kernel: [   56.915544] usb 2-1: reset SuperSpeed USB device number 13 using xhci-hcd

Tue Apr 19 14:42:57 2022 user.notice nlbwmon: Reloading nlbwmon due to ifup of loopback (lo)

Tue Apr 19 14:42:57 2022 kern.info kernel: [   57.355579] usb 2-1: USB disconnect, device number 13

Tue Apr 19 14:42:57 2022 kern.warn kernel: [   57.545609] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:42:57 2022 kern.warn kernel: [   57.755565] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:42:57 2022 kern.err kernel: [   57.962210] usb 2-1: device not accepting address 14, error -71

Tue Apr 19 14:42:58 2022 kern.warn kernel: [   58.152279] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:42:58 2022 kern.warn kernel: [   58.358948] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:42:58 2022 kern.err kernel: [   58.568939] usb 2-1: device not accepting address 15, error -71

Tue Apr 19 14:42:58 2022 kern.info kernel: [   58.570949] usb usb2-port1: attempt power cycle

Tue Apr 19 14:42:59 2022 kern.warn kernel: [   59.958894] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:43:00 2022 kern.warn kernel: [   60.165563] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:43:00 2022 kern.err kernel: [   60.372178] usb 2-1: device not accepting address 16, error -71

Tue Apr 19 14:43:00 2022 kern.warn kernel: [   60.772293] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:43:00 2022 kern.warn kernel: [   60.982259] usb 2-1: Device not responding to setup address.

Tue Apr 19 14:43:01 2022 kern.err kernel: [   61.188864] usb 2-1: device not accepting address 17, error -71

Tue Apr 19 14:43:01 2022 kern.err kernel: [   61.190765] usb usb2-port1: unable to enumerate USB device



目前只能在每次重启的时候先拔下 USB 网卡，重启之后再插回去。


插在 USB 2.0 口子上重启了两三次试了下，好像 2.0 的口没有这个问题。

请问这个是已知问题吗，有什么解决办法吗（换网卡，换某一版本的系统，延时启动的 usb hub?）



&mdash;
